from sulley import *
import random

s_initialize("HTML Anchors")

if s_block_start("All HTML"):
    s_static("<html><head><title>Sulley Says Hello!</title>")
    s_static("<script")
    s_static(">")
    s_static("document.getElementById(\"")
    s_string("0.372396489882")
    s_static("\").innerHTML=\"")
    s_string("0.214941827619")
    s_static("\"")
    s_static("</script>")
    s_static("</head><body>")
    s_static("<a href=\"http://127.0.0.1/")
    s_string("0.0538478115569")
    s_static("\">test 1</a>")

    s_static("<a href=\"http://127.0.0.1/")
    s_string("0.71416179634")
    s_static("\">    s_static("<img src=\"http://127.0.0.1")
    s_string("0.763347448813")
    s_static("\" alt=\"")
    s_string("alt img text")
    s_static("\" />")
</a>")

    s_static("<iframe")
    s_static(" name=\"")
    s_string("test 2")
    s_static("\"")
    s_static(" src=\"")
    s_string("test 2 source")
    s_static("\"")
    s_static(" onload=\"")
    s_string("test")
    s_static("\"")
    s_static(">")
    s_static("<a href=\"http://127.0.0.1/")
    s_string("0.0538478115569")
    s_static("\">test 1</a>")

    s_static("<a href=\"http://127.0.0.1/")
    s_string("0.71416179634")
    s_static("\">    s_static("<img src=\"http://127.0.0.1")
    s_string("0.763347448813")
    s_static("\" alt=\"")
    s_string("alt img text")
    s_static("\" />")
</a>")


    s_static("</iframe>")
    s_static("<object")
    s_static(" data=\"")
    s_string("test")
    s_static("\"")
    s_static(" name=\"")
    s_string("test object")
    s_static("\"")
    s_static(">")
    s_static("<a href=\"http://127.0.0.1/")
    s_string("0.0538478115569")
    s_static("\">test 1</a>")

    s_static("<a href=\"http://127.0.0.1/")
    s_string("0.71416179634")
    s_static("\">    s_static("<img src=\"http://127.0.0.1")
    s_string("0.763347448813")
    s_static("\" alt=\"")
    s_string("alt img text")
    s_static("\" />")
</a>")


    s_static("</object>")

s_block_end("All HTML")
s_static("<a href=\"http://127.0.0.1/")
s_checksum("All HTML", algorithm="sha1")
s_static("\">External Checksum Anchor</a>")
s_static("</body></html>")